name: Testing calls 

on: workflow_dispatch

jobs:

  test_calls:
    runs-on: ubuntu-latest

    steps: 
      - uses: actions/checkout@v3
      
      - name: install pandas
        run: pip install pandas

      - name: run python script
        run: python3 api-test.py
